Anki/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('flashcards/', include("flashcards.urls", namespace="flashcards")),
    path('', include("flashcards.urls", namespace="flashcards")),
    path('account/', include('account.urls', namespace='account')),
    path('reader/', include('reader.urls', namespace='reader')),
]

account/urls.py
from django.urls import path
from account.views import *
from django.contrib.auth import views as auth_views


app_name = 'account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

flashcards/urls.py
from django.urls import path

from flashcards.views import *

app_name = 'flashcards'
urlpatterns = [
    # 主页
    path('', index, name='dashboard'),
    # 单张卡片浏览
    path('<int:card_id>', card_detailview, name='card_detail'),
    # 下一张卡片
    path('next/', nextcardview, name='next'),
    # 背诵卡片
    path("recite/<int:card_id>/<int:rank>", cardreciteview, name="recite"),
    # 展示背诵数据
    path("recitedata/", recitedatadisplay, name="display"),
    # 展示单张卡片背诵数据
    path('card_recitedata_view/<int:card_id>/', card_recitedata_view, name='card_recitedata_view'),
    # 撤回：删除背诵数据
    path('undo/<int:card_id>', undo, name='undo'),
    # 列表的撤回：删除背诵记录
    path('undo_list/<int:list_id>/<int:progress>/', undo_list, name='undo_list'),
    # 查询某个单词
    path('search/', search, name='search'),
    # 网络搜索
    path('websearch/', websearch, name='websearch'),
    # 字典界面
    path('dict/', dict_search, name='dict'),
    path('create_wordlist_by_diff/', create_wordlist_by_diff, name='create_wordlist_by_diff'),
    path('create_wordlist_by_tag/', create_wordlist_by_tag, name='create_wordlist_by_tag'),
    path('delete_wordlist/<int:wordlist_id>/', delete_wordlist, name='delete_wordlist'),
    path('recite_wordlist/<int:wordlist_id>/<int:progress>/<int:rank>/', recite_wordlist, name='recite_wordlist'),
    path('word_add_tags/<int:word_id>/<slug:tag>/<int:section>/', word_add_tags, name='word_add_tags'),
    path('word_delete_tags/<int:word_id>/<int:tag_id>/<int:section>/', word_delete_tags, name='word_delete_tags'),
    path('word_edit/<int:word_id>/<int:section>/', word_edit, name='word_edit'),
    path('word_add/', word_add, name='word_add'),
    path('word_delete/<int:word_id>/', word_delete, name='word_delete'),
    path('settings/', settings_view, name='settings_view'),
    path('dict_query/', dict_query, name='dict_query'),
    path('get_example/', get_example, name='get_example'),
    path('export_card_as_txt/', export_card_as_txt, name='export_card_as_txt'),
    path('export_db/', export_db, name='export_db'),
    path('dict_query_get/<slug:query_word>/', dict_query_get, name='dict_query_get'),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import *


# Create your views here.
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully!')
                else:
                    return HttpResponse('Disabled Account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

account/templates/base.html
{% load static %}

<!doctype html>
<html lang="zh-CN">
<head>
    <!-- 必须的 meta 标签 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <!-- Bootstrap 的 CSS 文件 -->
    <link href="{% static "bootstrap.css" %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static '/img/favicon.ico' %}"/>
    {% block head %}{% endblock %}
    <style>
        @font-face {
            font-family: "_Gurmukhi MN";
            src: url('{% static '_Gurmukhi MN.ttc' %}');
        }

        @font-face {
            font-family: "icon";
            src: url('{% static 'font/SmileySans-Oblique.ttf.woff2' %}') format("woff");
        }

        .navbar-brand, .icon {
            font-family: icon, serif;
        }

        body {
            font-family: _Gurmukhi MN, serif;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-xl navbar-light bg-light text-center align-items-center sticky-top">
    <div class="container-fluid">
        <a href="{% url "flashcards:dashboard" %}" class="">
            <img src="{% static '/img/fuyou.png' %}" class="d-block h-100" alt="fail to load" width="50px"
                 height="50px">
        </a>
        <a class="navbar-brand fs-4" href="{% url "flashcards:dashboard" %}">OmniAnki</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse show" id="navbarText">
            <ul class="nav nav-tabs ">
                <li class="nav-item" id="Anki">
                    <a class="p-2 nav-link {% block Anki %}{% endblock %}"
                       href="{% url "flashcards:dashboard" %}">Anki</a>
                </li>
                <li class="nav-item">
                    <a class="p-2 nav-link {% block Recite %}{% endblock %}" href={% url 'flashcards:next' %}>Recite</a>
                </li>
                <li class="nav-item">
                    <a class="p-2 nav-link {% block Search %}{% endblock %}"
                       href={% url 'flashcards:search' %}>Search</a>
                </li>
                <li class="nav-item">
                    <a class="p-2 nav-link {% block Dict %}{% endblock %}" href={% url 'flashcards:dict' %}>Dict</a>
                </li>
                {% block navbar %}{% endblock %}
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid" id="content">
    {% block content %}
    {% endblock %}
</div>

<!-- 底部栏 -->
<footer class="container-fluid text-center fixed-bottom">
    {% block footer %}
    {% endblock %}
</footer>

<script src="{% static "popper.min.js" %}"></script>
<script src="{% static "bootstrap.js" %}"></script>
<script src="{% static 'jquery.min.js' %}"></script>
<script src="{% static 'js.cookie.min.js' %}"></script>
    <script>
    $("input").addClass("form-control");
    </script>
</body>
</html>