Anki/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('flashcards/', include("flashcards.urls", namespace="flashcards")),
    path('', include("flashcards.urls", namespace="flashcards")),
    path('account/', include('account.urls', namespace='account')),
    path('reader/', include('reader.urls', namespace='reader')),
]

account/urls.py
from django.urls import path
from account.views import *
from django.contrib.auth import views as auth_views


app_name = 'account'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

flashcards/urls.py
from django.urls import path

from flashcards.views import *

app_name = 'flashcards'
urlpatterns = [
    # 主页
    path('', index, name='dashboard'),
    # 单张卡片浏览
    path('<int:card_id>', card_detailview, name='card_detail'),
    # 下一张卡片
    path('next/', nextcardview, name='next'),
    # 背诵卡片
    path("recite/<int:card_id>/<int:rank>", cardreciteview, name="recite"),
    # 展示背诵数据
    path("recitedata/", recitedatadisplay, name="display"),
    # 展示单张卡片背诵数据
    path('card_recitedata_view/<int:card_id>/', card_recitedata_view, name='card_recitedata_view'),
    # 撤回：删除背诵数据
    path('undo/<int:card_id>', undo, name='undo'),
    # 列表的撤回：删除背诵记录
    path('undo_list/<int:list_id>/<int:progress>/', undo_list, name='undo_list'),
    # 查询某个单词
    path('search/', search, name='search'),
    # 网络搜索
    path('websearch/', websearch, name='websearch'),
    # 字典界面
    path('dict/', dict_search, name='dict'),
    path('create_wordlist_by_diff/', create_wordlist_by_diff, name='create_wordlist_by_diff'),
    path('create_wordlist_by_tag/', create_wordlist_by_tag, name='create_wordlist_by_tag'),
    path('delete_wordlist/<int:wordlist_id>/', delete_wordlist, name='delete_wordlist'),
    path('recite_wordlist/<int:wordlist_id>/<int:progress>/<int:rank>/', recite_wordlist, name='recite_wordlist'),
    path('word_add_tags/<int:word_id>/<slug:tag>/<int:section>/', word_add_tags, name='word_add_tags'),
    path('word_delete_tags/<int:word_id>/<int:tag_id>/<int:section>/', word_delete_tags, name='word_delete_tags'),
    path('word_edit/<int:word_id>/<int:section>/', word_edit, name='word_edit'),
    path('word_add/', word_add, name='word_add'),
    path('word_delete/<int:word_id>/', word_delete, name='word_delete'),
    path('settings/', settings_view, name='settings_view'),
    path('dict_query/', dict_query, name='dict_query'),
    path('get_example/', get_example, name='get_example'),
    path('export_card_as_txt/', export_card_as_txt, name='export_card_as_txt'),
    path('export_db/', export_db, name='export_db'),
    path('dict_query_get/<slug:query_word>/', dict_query_get, name='dict_query_get'),
]

reader/urls.py
from django.urls import path

from reader.views import *

app_name = 'reader'
urlpatterns = [
    # path('', index, name='dashboard'),
    # path('<slug:category_slug>/', views.product_list, name="product_list_by_category"),
    path('article/<int:article_id>/', article_detailview, name='article_detailview'),
    path('', article_list, name='article_list'),
    path('update_article/', update_article, name='update_article'),
    path('book/', read_book, name='read_book'),
    path('book/<int:book_id>/', book_detail, name='book_detail'),
    path('book_progress/', book_progress, name='book_progress'),
]

flashcards/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# import datetime


class Card(models.Model):
    group = models.CharField(max_length=20)
    question = models.CharField(max_length=200, default="none", blank=False)
    answer = models.CharField(max_length=200, default="none", blank=False)
    example = models.CharField(max_length=200)
    translation = models.CharField(max_length=200)
    extra = models.CharField(max_length=200)
    tags = TaggableManager()
    due = models.DateTimeField(null=False, default=datetime.date(1900, 1, 1))
    review_num = models.PositiveIntegerField(null=False, default=0)
    forget_num = models.PositiveIntegerField(null=False, default=0)
    ratio = models.PositiveIntegerField(null=False, default=0)
    interval = models.PositiveIntegerField(null=True, default=0, blank=True)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ('id',)
        # verbose_name = 'category'
        # verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('flashcards:card_detail',
                       args=[self.id])


# 每次使用时的数据，作为外键与卡片绑定
class Recitedata(models.Model):
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    rank = models.PositiveIntegerField(verbose_name="easy or diff?", default=0)
    card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name="recitedata")
    params = models.CharField(max_length=20000, default='{}')

    def __str__(self):
        return str(self.date) + ":" + str(self.rank)

    class Meta:
        ordering = ('date',)


class WordList(models.Model):
    owner = models.ForeignKey(User, models.CASCADE, related_name='owner')
    name = models.CharField(max_length=20, blank=False)
    wordlist = models.CharField(max_length=20000, blank=False)
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    progress = models.PositiveIntegerField(blank=False, default=0)
    len_list = models.PositiveIntegerField(blank=False, default=50)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('date',)


class Settings(models.Model):
    random_example = models.BooleanField(default=False)
    user = models.ForeignKey(User, models.CASCADE, related_name='settings')
    current_group = models.CharField(max_length=1000, default='{}')


class Dict(models.Model):
    headword = models.CharField(max_length=2000, blank=False)
    item = models.CharField(max_length=200000, blank=False)
    # coca排名
    coca = models.PositiveIntegerField(blank=False, default=0)

flashcards/forms.py
from django import forms
from .models import Card


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CreateForm(forms.Form):
    query2 = forms.CharField()


class CardForm(forms.ModelForm):
    class Meta:
        Model = Card
        fields = ['group', 'question', 'answer', 'example', 'translation', 'extra']

flashcards/views.py
import collections
import json
import random
import re
from datetime import timedelta, datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.db.models import Q
from django.http import JsonResponse, FileResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.decorators.http import require_POST
from taggit.models import Tag

from flashcards.utils import find_example_from_database
from .crontab import update_due_list
from .forms import *
from .models import *
from .utils import to_chinese
from .web_query import find_synonym


# 启动时执行的函数
def onstart():
    coca = {}
    # 将coca存入内存中
    with open('flashcards/static/dict/coca.txt', 'r', encoding='utf-8') as f:
        coca = json.loads(f.read())
    cache.set('coca', coca, timeout=None)


onstart()


# 首页
@login_required
def index(request):
    card_num = Card.objects.count()
    # 获取当前用户的单词列表
    wordlists = request.user.owner.all()
    # 获取过去七天的背诵数据
    now = timezone.now()
    # 七天前作为开始时间
    start = now - timedelta(days=7, hours=now.hour, minutes=now.minute, seconds=now.second)
    # 找到过去七天的背诵数据
    recitedata = Recitedata.objects.filter(date__gt=start)
    rank_count_by_day = []
    for i in range(1, 8):
        all_data = recitedata.filter(date__gt=start + timedelta(days=i), date__lt=start + timedelta(days=i + 1))
        counter = collections.Counter([data.rank for data in all_data])
        rank_count_by_day.append([counter[1], counter[2], counter[3], counter[4]])
    rank_count_by_rank = []
    for i in range(0, 4):
        rank_count_by_rank.append([rank_day[i] for rank_day in rank_count_by_day])
    # 仅返回有单词的tag
    tags = filter(lambda tag: len(Card.objects.filter(tags__in=[tag])), Tag.objects.all())
    return render(request, 'flashcards/anki.html',
                  {'len': card_num,
                   'lenlist': len(wordlists),
                   'wordlists': wordlists,
                   'tags': tags,
                   'recitedata': rank_count_by_rank,
                   })


# 单张卡片浏览
def card_detailview(request, card_id):
    # 从缓存中获取当前设置，若无则从数据库读取并存入缓存
    # random_example = request.user.settings.all()[0] if cache.get('random_example') is None else cache.get(
    #     'random_example')
    if cache.get('random_example') is None:
        # 判断该用户是否有setting
        settings = request.user.settings.all()
        if len(settings) == 0:
            add_setting = Settings(user=request.user)
            add_setting.save()
            random_example = add_setting
        else:
            random_example = request.user.settings.all()[0]
    else:
        random_example = cache.get('random_example')
    # 获取card实例
    card = get_object_or_404(Card, id=card_id)
    # 若当前设置为随机例句且是该卡片属于词汇分组
    if request.user.settings.all()[0].random_example and card.group[0:2] == "词汇":
        result = find_example_from_database(card.question)
        # 有可能查不到
        if len(result[0]) > 0:
            rand_index = random.randint(0, len(result[0]) - 1)
            card.example = result[0][rand_index]
            card.translation = result[1][rand_index]
    # 将例句中的此词标红
    if len(re.findall(r"[a-zA-Z]+", card.question)) > 0:
        reple = re.findall(r"[a-zA-Z]+", card.question)[0]
        card.example = card.example.replace(reple, "<span id='red'><b>" + reple + "</b></span>")
    return render(request,
                  'flashcards/card_detail.html',
                  {'object': card,
                   'tags': card.tags.all(),
                   'random_example': random_example
                   })


# 下一张卡片
@login_required
def nextcardview(request):
    # 有待改进，随机卡片操作十分耗时
    card = Card.objects.all()[random.randrange(1, Card.objects.count(), 1)]
    return redirect(card.get_absolute_url())


# 背诵
@login_required
def cardreciteview(request, card_id, rank):
    # 获取card实例
    card = get_object_or_404(Card, id=card_id)
    # 创建记忆数据并保存
    recitedata = Recitedata(rank=rank, card=card)
    recitedata.save()
    # 生成随机数并跳转至下一卡片
    card = Card.objects.all()[random.randrange(1, Card.objects.count(), 1)]
    return redirect(card.get_absolute_url())


# 展示背诵数据
@login_required
def recitedatadisplay(request):
    # 按rank排序，后续改进
    recitedata = Recitedata.objects.order_by("rank")
    # 使用set以防止card重复
    cards = set([data.card for data in recitedata])
    datas = [{'card': card, 'recitedata': card.recitedata.all()} for card in cards]
    return render(request,
                  'flashcards/recitedata.html',
                  {'datas': datas}
                  )


# 单张卡片背诵数据
def card_recitedata_view(request, card_id):
    card = get_object_or_404(Card, id=card_id)
    all_recitedata = card.recitedata.all()
    return render(request,
                  'flashcards/card_recitedata_detail.html',
                  {'all_recitedata': all_recitedata
                   })


# 修改到此
@login_required
def search(request):
    cd = {"query": ''}
    form = SearchForm(request.GET)
    no_result = False   # 无搜索结果标识符
    if form.is_valid():
        cd = form.cleaned_data
        if cd['query'][0:2] == 'T:':
            tag = get_object_or_404(Tag, slug=cd['query'][2:])
            cards = Card.objects.filter(tags__in=[tag])
        elif cd['query'][0:2] == 'G:':
            cards = Card.objects.filter(group__startswith=cd['query'][2:])
        else:
            cards = Card.objects.filter(
                Q(question__icontains=cd['query']) | Q(example__icontains=cd['query']))
            if not len(cards):
                no_result = True
            else:
                # 将搜索字段替换为红色
                for card in cards:
                    card.question = card.question.replace(cd['query'], "<span id='red'><b>" + cd['query'] + "</b></span>")
                    card.example = card.example.replace(cd['query'], "<span id='red'><b>" + cd['query'] + "</b></span>")
    else:
        form = SearchForm()
        return render(request, 'flashcards/search.html', {'searchvalue': cd['query'],
                                                          'form': form, 'no_result': no_result})
    return render(request, 'flashcards/search.html', {'cards': cards, 'searchvalue': cd['query'],
                                                      'form': form, 'no_result': no_result})


# 撤回：删除背诵记录
@login_required
def undo(request, card_id):
    # 需要撤回的卡片和需要删除背诵记录的卡是一张卡
    card = get_object_or_404(Card, id=card_id)
    card.recitedata.latest('date').delete()
    return redirect(card.get_absolute_url())


# 列表的撤回：删除背诵记录
@login_required
def undo_list(request, list_id, progress):
    wordlist = get_object_or_404(WordList, id=list_id)
    id_list = list(map(lambda dic: dic['id'], json.loads(wordlist.wordlist)))
    card_id = id_list[progress - 1]
    # 需要撤回到的卡片和需要删除背诵记录的卡是一张卡
    card = Card.objects.filter(id=card_id)
    latest_recitedata = card[0].recitedata.latest('date')
    recitedata_params = json.loads(latest_recitedata.params)
    card.due = datetime.strptime(recitedata_params['due'], "%Y-%m-%d %H:%M:%S.%f")
    card.review_num = recitedata_params['review_num']
    card.forget_num = recitedata_params['forget_num']
    card.ratio = recitedata_params['ratio']
    card.interval = recitedata_params['interval']
    card.save()
    latest_recitedata.delete()
    # 修改进度
    return redirect('flashcards:recite_wordlist', list_id, progress - 1, 0)


# 网络搜索
@login_required
def websearch(request):
    cd = {"query": ''}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
        words = find_synonym(cd['query'])
    else:
        form = SearchForm()
        words = []
    return render(request, 'flashcards/webquery.html',
                  {"words": words, 'searchvalue': cd['query'], 'form': form}, )


@login_required
def dict_search(request):
    cd = {"query": ''}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
        # 查词，返回单词和html文件
        html_result = ''
        queryword = cd['query']
        dict_query = Dict.objects.filter(headword=queryword)
        if len(dict_query) == 0:
            dict_query = Dict.objects.filter(headword=queryword.lower())
            if len(dict_query) == 0:
                html_result = 'No Match!'
        html_result = dict_query[0].item
    else:
        form = SearchForm()
        html_result = ''

    return render(request, 'flashcards/dict.html',
                  {'html_result': html_result, 'form': form, 'searchvalue': cd['query'],
                   })


@login_required
def create_wordlist_by_diff(request):
    cd = {"query": 'list'}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data
    # 找到最近的三个复习data并累计，生成一个字典
    rank_sum_dict = map(lambda card: {'id': card.id, 'rank_sum': sum(
        sorted([Recitedata.rank for Recitedata in card.recitedata.order_by('-date')], reverse=True)[0:3])
    if len(card.recitedata.all()) > 2
    else sum([Recitedata.rank for Recitedata in card.recitedata.order_by('-date')])}
                        , Card.objects.all())
    # 按rank排序，取前五十个值
    # 不知道为什么id列表总为空
    # id_list = [dic['id'] for dic in sorted(list(rank_sum_dict), key=lambda dic: dic['rank_sum'], reverse=True)[0:50]]
    # id_list = list(
    #     map(lambda dic: dic['id'], sorted(list(rank_sum_dict), key=lambda dic: dic['rank_sum'], reverse=True)[0:50]))
    # print(id_list)
    sort_list = sorted(list(rank_sum_dict), key=lambda dic: dic['rank_sum'], reverse=True)[0:50]
    wordlist = WordList(owner=request.user, name=cd['query'], wordlist=json.dumps(sort_list)
                        , len_list=len(sort_list))
    wordlist.save()
    messages.success(request, '单词列表创建成功')
    return redirect('flashcards:dashboard')


@login_required
def create_wordlist_by_tag(request):
    cd = {"query": 'list', "tag": 'marked'}
    form = SearchForm(request.GET)
    if form.is_valid():
        cd = form.cleaned_data

flashcards/templates/flashcards/anki.html
{% extends "flashcards/base.html" %}
{% load static %}
{% load flashcards_tags %}
{% block title %}Anki{% endblock %}
{% block head %}
    <script src="{% static "echarts.js" %}"></script>
    <style>
        a {
            text-decoration: none;
        }

        #red {
            color: red;
        }

        #id_query {
            margin-top: 2%;
        }


    </style>
{% endblock %}
{% block Anki %} active{% endblock %}
{% block navbar %}
    <li class="nav-item">
        <a class="p-2 nav-link" href={% url 'reader:article_list' %}>Reader</a>
    </li>
{% endblock %}
{% block content %}
    <div class="card h-100 shadow mt-2">
        <div class="card-header d-flex">
            <h5 class="icon d-inline">Dashboard</h5>
            <div class="ms-auto"><span class="badge rounded-pill bg-primary"
                  onClick="location.href='{% url 'account:logout' %}'">Logout</span>
            <span class="badge rounded-pill bg-primary" onClick="location.href='{% url 'flashcards:settings_view' %}'">Settings</span>
        </div>
            </div>
        <div class="card-body">
            <p class="card-text">Current word bank has <span class="bg-light">{{ len }}</span> words, <span class="bg-light">{{ lenlist }}</span> wordlists.
            </p>
            <!--创建单词列表表单-->
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample"
                 aria-labelledby="offcanvasExampleLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasExampleLabel">创建单词列表</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                            aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div>
                        <h6 class="lead h6">以难度创建</h6>
                        <form id='form1' class="align-items-center col-12 " method="get"
                              action="{% url 'flashcards:create_wordlist_by_diff' %}">

                            <div class="form-floating mb-3 mt-3">
                                <input type="text" class="form-control" id="floatingInput" placeholder="list"
                                       name="query">
                                <label for="floatingInput">列表名：</label>
                            </div>

                            {% csrf_token %}

                        </form>
                    </div>
                    <div>
                        <h6 class="lead h6">以标签创建</h6>
                        <form id='form2' class="align-items-center col-12 " method="get"
                              action="{% url 'flashcards:create_wordlist_by_tag' %}">

                            <div class="form-floating mb-3">

                                <select class="form-select" id="tagfloatingSelect"
                                        aria-label="Floating label select example"
                                        name="tag">

                                    {% for tag in tags %}
                                        <option value="{{ tag }}" name="{{ tag }}">{{ tag }}</option>
                                    {% endfor %}

                                </select>
                                <label for="tagfloatingSelect">请选择标签</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="floatingInput2" placeholder="list"
                                       name="query">
                                <label for="floatingInput2">列表名：</label>
                            </div>

                            {% csrf_token %}

                        </form>
                    </div>
                </div>
            </div>
            <!--创建单词列表表单结束-->
            <!-- 单词列表 -->
            <div class="card-text">
                <ol class="list-group list-group-numbered">
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a class="" data-bs-toggle="offcanvas"
                                   href="#offcanvasExample" role="button"
                                   aria-controls="offcanvasExample">Click here to create a wordlist!</a>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a class='link' href="{% url 'flashcards:next' %}">Random word</a>
                            </div>
                        </div>
                    </li>
                    {% for wordlist in wordlists %}
                        {% if wordlist.name == "due" %}
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">
                                        <a class='link' href="
                                                {% if wordlist.progress != wordlist.len_list %}{% url 'flashcards:recite_wordlist' wordlist.id wordlist.progress 0 %}{% else %}{% url 'flashcards:recite_wordlist' wordlist.id 0 0 %}{% endif %}">{{ wordlist.name }}</a>
                                        <span class="badge rounded-pill bg-primary">{{ wordlist.progress }}/{{ wordlist.len_list }}</span>
                                    </div>
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% for wordlist in wordlists %}
                        {% if wordlist.name != "due" %}
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a class='link' href="









                                            {% if wordlist.progress != wordlist.len_list %}{% url 'flashcards:recite_wordlist' wordlist.id wordlist.progress 0 %}{% else %}{% url 'flashcards:recite_wordlist' wordlist.id 0 0 %}{% endif %}">{{ wordlist.name }}</a>
                                        <span class="badge rounded-pill bg-primary">{{ wordlist.progress }}/{{ wordlist.len_list }}</span>
                                        <span class="badge rounded-pill bg-danger"
                                              onClick="location.href='{% url 'flashcards:delete_wordlist' wordlist.id %}'">Delete</span>
                                    </div>
                                </div>
                            </li>
                        {% endif %}

                    {% endfor %}
                </ol>
            </div>
            <!-- 统计图表 -->
            <div class="container text-center mt-2">
                <div class="row">
                    <div class="col-12">
                        <div id="main2" style="width: 100%;height:400px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block script %}
    // 图表
    var chartDom = document.getElementById('main2');
    var myChart = echarts.init(chartDom);
    var option;
    var type = {"1":'Easy',"2":'Mid',"3":'Diff',"4":'Forget'};
    option = {
    title: {
    left:'center',
    text: 'ReciteData',
    textStyle: {
    color: '#235894'
    }
    },
    angleAxis: {
    type: 'category',
    data: ['6 day', '5 day', '4 day', '3 day', '2 day', '1 day', 'Today']
    },
    radiusAxis: {},
    polar: {},
    series: [

    {% for data in recitedata %}
        {
        type: 'bar',
        data: {{ data }},
        coordinateSystem: 'polar',
        name: type['{{ forloop.counter }}'],
        stack: 'a',
        emphasis: {
        focus: 'series'
        }
        },
    {% endfor %}

    ],
    legend: {
    show: true,
    data: ['Easy', 'Mid', 'Diff','Forget'],
    top: 'bottom',
    }
    };

    option && myChart.setOption(option);
{% endblock %}

flashcards/templates/flashcards/card_base.html
{% extends "flashcards/base.html" %}
{% load static %}
{% load flashcards_tags %}
{% block title %}Card{% endblock %}

{% block head %}
    <style>
        .link {
            text-decoration: none;
            font-weight: bold;
        }

        .word.accordion-button::after {
            display: none;
        }

        button {
            -webkit-user-select: text; /* Chrome all / Safari all */
            -moz-user-select: text; /* Firefox all */
            -ms-user-select: text; /* IE 10+ */
            user-select: text;
        }
    </style>
{% endblock %}

{% block navbar %}
    <!--添加编辑栏-->
    <li class="nav-item">
        <a class="p-2 nav-link active" href={% url 'flashcards:next' %}>Recite</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="Edit" role="button" data-bs-toggle="dropdown"
           aria-expanded="false">
            Card
        </a>
        <ul class="dropdown-menu bg-light text-center" aria-labelledby="Edit">
            <li><a class="dropdown-item" href="{% url 'flashcards:word_add_tags' object.id 'marked' 0 %}">Mark!</a></li>
            <li><a class="dropdown-item " href="#EditCard" data-bs-toggle="offcanvas" role="button"
                   aria-controls="EditCard">Edit</a></li>
            <li><a class="dropdown-item" href="{% url 'flashcards:word_delete' object.id %}">Delete</a></li>
            <li><a class="dropdown-item" href="{% url 'flashcards:word_add' %}">Add Word</a></li>
        </ul>
    </li>
{% endblock %}
{% block content %}

    <!-- 卡片正面 -->
    <div class="card h-100 shadow mt-2">
        <div class="card-header align-items-center">
            <div class="h6 d-flex flex-nowrap pt-2">
                <span>{{ object.group }}</span>
                <div class="ms-auto row">
                    <div class="col">
                        {% for tag in tags %}
                            <span class="badge rounded-pill bg-primary position-relative">{{ tag }}
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                      onClick="location.href='{% block deletetags %}{% endblock %}'">
    X
  </span></span>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% block progressbar %}
            {% endblock %}
        </div>
        <div class="accordion accordion-flush shadow-sm" id="accordionFlushExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed " type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne"
                            onclick="audioplay()">
                        <div class="link">{{ object.question |pureword |safe }}</div>
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne">
                    <div class="accordion-body">{{ object.answer |safe |linebreaks }}</div>
                </div>
            </div>
            {% if object.example %}
                <div class="accordion-item" id="example">
                    <h2 class="accordion-header" id="flush-headingTwo">
                        <button id="example_button" class="accordion-button collapsed" type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseTwo" aria-expanded="false"
                                aria-controls="flush-collapseTwo">
                            <div>{{ object.example |safe }}</div>
                        </button>
                    </h2>
                    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo">
                        <div class="accordion-body">{{ object.translation |safe }}</div>
                    </div>
                </div>{% endif %}
            {% if object.extra %}
                <div class="accordion-item" id="extra">
                    <h2 class="accordion-header" id="flush-headingThree">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseThree" aria-expanded="true"
                                aria-controls="flush-collapseThree">
                            EXTRA
                        </button>
                    </h2>
                    <div id="flush-collapseThree" class="accordion-collapse  open" aria-labelledby="flush-headingThree"
                         data-bs-parent="#accordionFlushExample">
                        <div id="extra_button" class="accordion-body">{{ object.extra |safe }}</div>
                    </div>
                </div>{% endif %}
        </div>
    </div>
{% endblock %}


{% block domready %}
{% endblock %}