Anki/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('flashcards/', include("flashcards.urls", namespace="flashcards")),
    path('', include("flashcards.urls", namespace="flashcards")),
    path('account/', include('account.urls', namespace='account')),
    path('reader/', include('reader.urls', namespace='reader')),
]

reader/urls.py
from django.urls import path

from reader.views import *

app_name = 'reader'
urlpatterns = [
    # path('', index, name='dashboard'),
    # path('<slug:category_slug>/', views.product_list, name="product_list_by_category"),
    path('article/<int:article_id>/', article_detailview, name='article_detailview'),
    path('', article_list, name='article_list'),
    path('update_article/', update_article, name='update_article'),
    path('book/', read_book, name='read_book'),
    path('book/<int:book_id>/', book_detail, name='book_detail'),
    path('book_progress/', book_progress, name='book_progress'),
]

reader/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=50, blank=False)
    content = models.CharField(max_length=200000, blank=False)
    top_image_url = models.CharField(max_length=200, default="none")

    class Meta:
        ordering = ('-id',)


class Book(models.Model):
    title = models.CharField(max_length=50, blank=False)
    content = models.BinaryField(blank=False)
    progress = models.FloatField(default=0, blank=False)
    top_image_url = models.CharField(max_length=200, default="none")

reader/views.py
import newspaper
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from .models import *


def article_detailview(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    return render(request,
                  'reader/read_article.html',
                  {'article': article
                   })


def article_list(request):
    articles = Article.objects.all()
    paginator = Paginator(articles, 12)  # 20 articles in each page
    page = request.GET.get('page')  # 当前页数

    try:
        current_page_articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        current_page_articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        current_page_articles = paginator.page(paginator.num_pages)
    return render(request,
                  'reader/article_list.html',
                  {'articles': current_page_articles,
                   'page': page,
                   })


def update_article(request):
    urls = ['https://www.cnbc.com/', 'https://thenextweb.com/', 'https://www.cnn.com/', 'https://www.wired.com/']
    # 若是主动提交且含有地址，则只要这个url
    if 'url' in request.POST and request.POST['url'][0:4] == 'http':
        urls = [request.POST['url']]
    count_num = 0
    # 删除所有新闻，更新100篇新闻
    Article.objects.all().delete()
    # 循环urls列表，直到50篇新闻
    for url in urls:
        cnn = newspaper.build(urls[0], languange='en', memoize_articles=False)
        with open('./log.txt', 'a') as f:
            f.write(f"开始更新文章,来自{url}，共有{len(cnn.articles)}篇文章\n")
        for article in cnn.articles:
            try:
                article.download()
                article.parse()
            except Exception as e:
                with open('./log.txt', 'a') as f:
                    f.write(f'{e}\n')
                continue
            if article.text == "" or article.title == "" or len(article.text.strip()) < 2000:
                with open('./log.txt', 'a') as f:
                    f.write(f'太短！只有{len(article.text)}字符\n')
                continue
            else:
                count_num += 1
                with open('./log.txt', 'a') as f:
                    f.write(f'成功导入第{count_num}/100个，有{len(article.text)}个字符\n')
                art_model = Article(title=article.title, content=article.text)
                if article.top_image != '':
                    art_model.top_image_url = article.top_image
                art_model.save()

                if count_num == 100:
                    with open('./log.txt', 'a') as f:
                        f.write('全部导入!\n')
                    break
        if count_num == 100:
            break

    messages.success(request, f"更新{count_num}篇文章")
    return JsonResponse({'status': 'ok'})


def read_book(request):
    books = Book.objects.all()
    paginator = Paginator(books, 10)  # 20 articles in each page
    page = request.GET.get('page')  # 当前页数

    try:
        current_page_books = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        current_page_books = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        current_page_books = paginator.page(paginator.num_pages)
    return render(request,
                  'reader/book_list.html',
                  {'books': current_page_books,
                   'page': page,
                   }
                  )


def book_detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    # 字节码转换
    book.content = book.content.decode()
    return render(request,
                  'reader/book_detail.html',
                  {'book': book,
                   })


def book_progress(request):
    progress = request.POST.get('progress')
    book_id = request.POST.get('book_id')
    book = get_object_or_404(Book, id=book_id)
    if progress and book_id:
        book.progress = progress
        book.save()
        return JsonResponse({'status': '保存成功'})
    return JsonResponse({'progress': book.progress})

reader/templates/reader/article_list.html
{% extends "flashcards/base.html" %}
{% load static %}

{% block title %}Reader{% endblock %}


{% block navbar %}
    <li class="nav-item">
        <a class="p-2 nav-link active" href={% url 'reader:article_list' %}>Reader</a>
    </li>
    <li class="nav-item">
        <a class="p-2 nav-link" href={% url 'reader:read_book' %}>Book</a>
    </li>
{% endblock %}

{% block content %}
    <div class="row row-cols-md-3 row-cols-sm-1 g-4">
        {% for article in articles %}
            <div class="col-sm-12 col-md-4">
                <div class="card h-100 shadow placeholder-glow">
                    {% if article.top_image_url != 'none' %}
                        <img src="{{ article.top_image_url }}" class="card-img-top placeholder" alt="..."
                             onclick="location.href='{% url 'reader:article_detailview' article.id %}'">
                    {% endif %}
                    <div class="card-body">
                        <a class="card-title h5 "
                           href="{% url 'reader:article_detailview' article.id %}">{{ article.title| truncatewords:10 }}</a>
                        <p class="card-text ">{{ article.content | truncatewords:20 }}</p>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>

    <nav class="mt-2 text-center" aria-label="Page navigation example">
        <ul class="pagination row g-0 align-items-center">
            <li class="page-item col-2 {% if articles.has_previous %}{% else %}disabled{% endif %}">
                <a class="page-link" href="?page={% if articles.has_previous %}{{ articles.previous_page_number }}{% else %}{{ articles.number }}{% endif %}">Pre</a>
            </li>
            {% for page_num in articles.paginator.page_range %}
                <li class="page-item col-2 {% if  articles.number  == page_num %} active{% endif %}">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
            {% endfor %}
            <li class="page-item col-4 {% if articles.has_next %}{% else %}disabled{% endif %}">
                <a class="page-link " href="?page={% if articles.has_next %}{{ articles.next_page_number }}{% else %}{{ articles.number }}{% endif %}">Next</a>
            </li>
        </ul>
    </nav>

{% endblock %}

{% block domready %}
    //图片加载
    var t_img; // 定时器
    var isLoad = true; // 控制变量

    // 判断图片加载状况，加载完成后回调
    isImgLoad(function(){
    // 加载完成的回调函数
    $('img').removeClass('placeholder')
    });

    // 判断图片加载的函数
    function isImgLoad(callback){
    // 注意我的图片类名都是cover，因为我只需要处理cover。其它图片可以不管。
    // 查找所有封面图，迭代处理
    $('img').each(function(){
    // 找到为0就将isLoad设为false，并退出each
    if(this.height === 0){
    isLoad = false;
    return false;
    }

    });
    // 为true，没有发现为0的。加载完毕
    if(isLoad){
    clearTimeout(t_img); // 清除定时器
    // 回调函数
    callback();
    // 为false，因为找到了没有加载完成的图，将调用定时器递归
    }else{
    isLoad = true;
    t_img = setTimeout(function(){
    isImgLoad(callback); // 递归扫描
    },500); // 我这里设置的是500毫秒就扫描一次，可以自己调整
    }
    }
{% endblock %}

reader/templates/reader/book_detail.html
{% extends "flashcards/base.html" %}
{% load static %}

{% block title %}Books{% endblock %}

{% block head %}
    <style>
        body{
            margin-left: 0% !important;
            margin-right: 0% !important;
        }
        #footer {
            position: fixed;
            bottom: 0;
            padding-bottom: 0;
            margin-bottom: 0;
        }
    </style>
{% endblock %}

{% block navbar %}
    <li class="nav-item">
        <a class="p-2 nav-link" href={% url 'reader:article_list' %}>Reader</a>
    </li>
    <li class="nav-item">
        <a class="p-2 nav-link active" href={% url 'reader:read_book' %}>Book</a>
    </li>
{% endblock %}

{% block content %}
        <div class="card h-100 shadow placeholder-glow m-2">
        <div class="card-body p-8">{{ book.content |safe}}
        </div></div>
{% endblock %}

{% block footer %}
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
    <button  class="btn btn-outline-primary" id="getProgress" data-bs-toggle="popover" title="保存成功" data-bs-content="">保存进度!</button>
    <button  class="btn btn-outline-primary" id="backToProgress" >回溯进度！</button>
    </div>
{% endblock %}

{% block script %}
    progress = 0
    function saveCurrentProgress(){
        // 页面的总高度
        let pageHeight = document.body.scrollHeight || document.documentElement.scrollHeight;
        // 浏览器视口高度
        let windowHeight = document.documentElement.clientHeight || document.body.clientHeight;
        // 可滚动的高度
        let scrollAvail = pageHeight - windowHeight;
        // 获取滚动条的高度
        let scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
        // console.log(String(scrollTop/scrollAvail))
        progress = scrollTop/scrollAvail
        $.post('{% url "reader:book_progress" %}',
            {
                progress: progress,
                book_id: {{ book.id }},
            },
            function(data){
                //alert(String(progress))
                alert(data['status'])
            }
          );
    }
    function backToSavedProgress(){
        // 页面的总高度
        let pageHeight = document.body.scrollHeight || document.documentElement.scrollHeight;
        // 浏览器视口高度
        let windowHeight = document.documentElement.clientHeight || document.body.clientHeight;
        // 可滚动的高度
        let scrollAvail = pageHeight - windowHeight;
        // 获取滚动条的高度
        let scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
        console.log(String(progress*scrollAvail))
        //$('body').scrollTop(progress*scrollAvail)
        $.post('{% url "reader:book_progress" %}',
            {
                book_id: {{ book.id }},
            },
            function(data){
                //alert(data['progress'])
                $('html,body').animate({scrollTop:data['progress']*scrollAvail}, 800);
            }
          );
        }


    $("#getProgress").click(function(){
        saveCurrentProgress()
})
    $("#backToProgress").click(function(){
        backToSavedProgress()
})

{% endblock %}

reader/templates/reader/book_list.html
{% extends "flashcards/base.html" %}
{% load static %}

{% block title %}Reader{% endblock %}


{% block navbar %}
    <li class="nav-item">
        <a class="p-2 nav-link" href={% url 'reader:article_list' %}>Reader</a>
    </li>
    <li class="nav-item">
        <a class="p-2 nav-link active" href={% url 'reader:read_book' %}>Book</a>
    </li>
{% endblock %}

{% block content %}
    <div class="row row-cols-md-3 row-cols-sm-1 g-4">
        {% for article in books %}
            <div class="col-sm-12 col-md-4">
                <div class="card h-100 shadow placeholder-glow">
                    <img src="{% static 'img/books/cover.jpg' %}" class="card-img-top placeholder-glow" alt="..."
                         onclick="location.href='{% url 'reader:book_detail' article.id %}'">
                    <div class="card-body">
                        <a class="card-title h5"
                           href="{% url 'reader:book_detail' article.id %}">{{ article.title| truncatewords:10 }}</a>
                        <p class="card-text">blablabla</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav class="mt-2 text-center" aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if books.has_previous %}{% else %}disabled{% endif %}">
                <a class="page-link" href="?page=

                        {% if books.has_previous %}{{ books.previous_page_number }}{% else %}{{ books.number }}{% endif %}">Previous</a>
            </li>
            {% for page_num in books.paginator.page_range %}
                <li class="page-item {% if  books.number  == page_num %}disabled{% endif %}"><a class="page-link"
                                                                                                href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
            {% endfor %}
            <li class="page-item {% if books.has_next %}{% else %}disabled{% endif %}">
                <a class="page-link " href="?page=

                        {% if books.has_next %}{{ books.next_page_number }}{% else %}{{ books.number }}{% endif %}">Next</a>
            </li>
        </ul>
    </nav>

{% endblock %}

{% block domready %}
    //图片加载
    var t_img; // 定时器
    var isLoad = true; // 控制变量

    // 判断图片加载状况，加载完成后回调
    isImgLoad(function(){
    // 加载完成的回调函数
    $('img').removeClass('placeholder')
    });

    // 判断图片加载的函数
    function isImgLoad(callback){
    // 注意我的图片类名都是cover，因为我只需要处理cover。其它图片可以不管。
    // 查找所有封面图，迭代处理
    $('img').each(function(){
    // 找到为0就将isLoad设为false，并退出each
    if(this.height === 0){
    isLoad = false;
    return false;
    }

    });
    // 为true，没有发现为0的。加载完毕
    if(isLoad){
    clearTimeout(t_img); // 清除定时器
    // 回调函数
    callback();
    // 为false，因为找到了没有加载完成的图，将调用定时器递归
    }else{
    isLoad = true;
    t_img = setTimeout(function(){
    isImgLoad(callback); // 递归扫描
    },500); // 我这里设置的是500毫秒就扫描一次，可以自己调整
    }
    }
{% endblock %}

reader/templates/reader/read_article.html
{% extends "flashcards/base.html" %}
{% load static %}

{% block title %}News{% endblock %}

{% block navbar %}
    <li class="nav-item">
        <a class="p-2 nav-link active" href={% url 'reader:article_list' %}>Reader</a>
    </li>
    <li class="nav-item">
        <a class="p-2 nav-link" href={% url 'reader:read_book' %}>Book</a>
    </li>
{% endblock %}

{% block content %}
    <div class="card h-100 shadow placeholder-glow m-2">
        <div class="card-header h5">{{ article.title }}</div>
        <div class="card-body p-8">
            {% if article.top_image_url != 'none' %}
                <div class="text-center">
                <img src="{{ article.top_image_url }}" class="card-img-top placeholder w-75" alt="..."
                     onclick="location.href='{% url 'reader:article_detailview' article.id %}'">
                </div>
            {% endif %}
            <p class="card-text"> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ article.content | linebreaksbr }}</p>

        </div>
    </div>
{% endblock %}


{% block domready %}
    //图片加载
var t_img; // 定时器
var isLoad = true; // 控制变量

// 判断图片加载状况，加载完成后回调
isImgLoad(function(){
    // 加载完成的回调函数
    $('img').removeClass('placeholder')
});

// 判断图片加载的函数
function isImgLoad(callback){
    // 注意我的图片类名都是cover，因为我只需要处理cover。其它图片可以不管。
    // 查找所有封面图，迭代处理
    $('img').each(function(){
        // 找到为0就将isLoad设为false，并退出each
        if(this.height === 0){
            isLoad = false;
            return false;
        }

    });
    // 为true，没有发现为0的。加载完毕
    if(isLoad){
        clearTimeout(t_img); // 清除定时器
        // 回调函数
        callback();
    // 为false，因为找到了没有加载完成的图，将调用定时器递归
    }else{
        isLoad = true;
        t_img = setTimeout(function(){
            isImgLoad(callback); // 递归扫描
        },500); // 我这里设置的是500毫秒就扫描一次，可以自己调整
    }
}
{% endblock %}